import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const employeeId = searchParams.get('employeeId');

    const where: Record<string, unknown> = {};

    if (employeeId) {
      where.employeeId = employeeId;
    }

    const warnings = await db.warning.findMany({
      where,
      include: {
        employee: {
          select: {
            id: true,
            fullName: true,
            employeeId: true,
          },
        },
        createdBy: {
          select: {
            id: true,
            name: true,
            email: true,
          },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    return NextResponse.json({
      success: true,
      data: {
        warnings: warnings.map((w) => ({
          ...w,
          createdAt: w.createdAt.toISOString(),
          updatedAt: w.updatedAt.toISOString(),
        })),
      },
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Internal server error';
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { employeeId, reason, isAutoGenerated, absentDates, createdById } = body;

    if (!employeeId || !reason || !createdById) {
      return NextResponse.json(
        { success: false, error: 'employeeId, reason, and createdById are required' },
        { status: 400 }
      );
    }

    // Verify employee exists
    const employee = await db.employee.findUnique({ where: { id: employeeId } });

    if (!employee) {
      return NextResponse.json(
        { success: false, error: 'Employee not found' },
        { status: 404 }
      );
    }

    // Verify creator exists — if not, look up first available user as fallback
    let finalCreatedById = createdById;
    const creator = await db.user.findUnique({ where: { id: createdById } });
    if (!creator) {
      const fallbackUser = await db.user.findFirst({ select: { id: true } });
      if (fallbackUser) {
        finalCreatedById = fallbackUser.id;
      } else {
        return NextResponse.json(
          { success: false, error: 'No user found in the system' },
          { status: 400 }
        );
      }
    }

    const warning = await db.$transaction(async (tx) => {
      const newWarning = await tx.warning.create({
        data: {
          employeeId,
          reason,
          isAutoGenerated: isAutoGenerated || false,
          absentDates: absentDates ? JSON.stringify(absentDates) : null,
          createdById: finalCreatedById,
        },
        include: {
          employee: {
            select: { fullName: true, employeeId: true, rating: true },
          },
        },
      });

      // Deduct 0.5 stars for the warning
      const newRating = Math.max(0, Math.round((newWarning.employee.rating - 0.5) * 10) / 10);
      await tx.employee.update({
        where: { id: employeeId },
        data: { rating: newRating },
      });

      // Create notification for super admins
      const superAdmins = await tx.user.findMany({
        where: { role: 'super_admin' },
        select: { id: true },
      });

      for (const admin of superAdmins) {
        await tx.notification.create({
          data: {
            userId: admin.id,
            title: 'New Warning Issued',
            message: `A warning has been issued for employee ${newWarning.employee.fullName} (${newWarning.employee.employeeId}). Reason: ${reason}`,
            type: 'warning',
          },
        });
      }

      return newWarning;
    });

    return NextResponse.json(
      {
        success: true,
        data: {
          warning: {
            ...warning,
            createdAt: warning.createdAt.toISOString(),
            updatedAt: warning.updatedAt.toISOString(),
          },
        },
      },
      { status: 201 }
    );
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : 'Internal server error';
    return NextResponse.json(
      { success: false, error: message },
      { status: 500 }
    );
  }
}
