'use client';

import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  Bell,
  FileText,
  AlertTriangle,
  DollarSign,
  CheckCheck,
  Clock,
  CheckCircle2,
  XCircle,
  HourglassIcon,
  Plus,
  Search as SearchIcon,
  Loader2,
  CalendarDays,
  Ban,
  Printer,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command';
import { toast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';
import { useAuthStore } from '@/store/auth-store';

/* ───────── types ───────── */

// Leave Request
interface LeaveRequest {
  id: string;
  employeeId: string;
  employee: {
    id: string;
    fullName: string;
    employeeId: string;
    position: string | null;
    companyName: string | null;
    phone: string | null;
    nationality: string | null;
  };
  type: 'casual' | 'sick' | 'annual' | 'emergency' | 'marriage' | 'other';
  otherTypeText?: string | null;
  startDate: string;
  endDate: string;
  totalDays: number;
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  createdAt: string;
  updatedAt: string;
  reviewedBy: string | null;
  reviewedAt: string | null;
}

// Cancellation Request
interface CancellationRequest {
  id: string;
  employeeId: string;
  employee: {
    id: string;
    fullName: string;
    employeeId: string;
    position: string | null;
    phone: string | null;
  };
  reason: string;
  status: 'pending' | 'approved' | 'rejected';
  createdAt: string;
  updatedAt: string;
  reviewedBy: string | null;
  reviewedAt: string | null;
}

// Employee for dropdown
interface EmployeeOption {
  id: string;
  fullName: string;
  employeeId: string;
  phone: string | null;
  position: string | null;
  companyName: string | null;
  nationality: string | null;
  currentSite: string | null;
}

// Notification types (warnings/fines)
interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  type: 'request' | 'warning' | 'fine';
  read: boolean;
  createdAt: string;
  updatedAt: string;
}

interface Warning {
  id: string;
  employeeId: string;
  reason: string;
  isAutoGenerated: boolean;
  absentDates: string | null;
  createdAt: string;
  updatedAt: string;
  employee: { id: string; fullName: string; employeeId: string };
  createdBy: { id: string; name: string; email: string };
}

interface Fine {
  id: string;
  employeeId: string;
  reason: string;
  amount: number;
  createdAt: string;
  updatedAt: string;
  employee: { id: string; fullName: string; employeeId: string };
  createdBy: { id: string; name: string; email: string };
}

/* ───────── helpers ───────── */
const MONTHS = [
  { value: '01', label: 'Jan' },
  { value: '02', label: 'Feb' },
  { value: '03', label: 'Mar' },
  { value: '04', label: 'Apr' },
  { value: '05', label: 'May' },
  { value: '06', label: 'Jun' },
  { value: '07', label: 'Jul' },
  { value: '08', label: 'Aug' },
  { value: '09', label: 'Sep' },
  { value: '10', label: 'Oct' },
  { value: '11', label: 'Nov' },
  { value: '12', label: 'Dec' },
];

const currentYear = new Date().getFullYear();
const currentMonth = new Date().getMonth() + 1;
const YEARS = Array.from({ length: 5 }, (_, i) => String(currentYear - 2 + i));

function formatDate(dateStr: string): string {
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  } catch {
    return dateStr;
  }
}

function formatFormalDate(dateStr: string): string {
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  } catch {
    return dateStr;
  }
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-SA', {
    style: 'currency',
    currency: 'SAR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  }).format(amount);
}

function calculateTotalDays(start: string, end: string): number {
  const startDate = new Date(start);
  const endDate = new Date(end);
  const diffTime = Math.abs(endDate.getTime() - startDate.getTime());
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return diffDays + 1; // inclusive
}

// Leave application HTML (matching the provided image style)
function generateLeaveApplicationHtml(req: LeaveRequest): string {
  const typeLabels: Record<string, string> = {
    casual: 'Casual',
    sick: 'Sick',
    annual: 'Annual',
    emergency: 'Emergency',
    marriage: 'Marriage',
    other: `Other (${req.otherTypeText || ''})`,
  };
  const leaveType = typeLabels[req.type] || req.type;
  const submissionDate = formatFormalDate(new Date().toISOString());

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Leave Application - ${req.employee.fullName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Times New Roman', Times, serif;
      background: #f0f0f0;
      padding: 40px 20px;
      display: flex;
      justify-content: center;
    }
    .leave-form {
      max-width: 900px;
      width: 100%;
      background: white;
      border: 1px solid #999;
      box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    }
    /* Header */
    .header {
      text-align: center;
      padding: 20px 20px 10px;
      border-bottom: 2px solid #c00;
    }
    .header h1 {
      font-size: 28px;
      font-weight: bold;
      letter-spacing: 2px;
      color: #8b0000;
      margin-bottom: 4px;
    }
    .header h2 {
      font-size: 18px;
      font-weight: normal;
      color: #333;
      margin-top: 4px;
    }
    /* Content */
    .content {
      padding: 24px 30px 30px;
    }
    .field-row {
      display: flex;
      margin-bottom: 16px;
      border-bottom: 1px solid #ddd;
      padding-bottom: 8px;
    }
    .field-label {
      width: 180px;
      font-weight: bold;
      color: #1a1a1a;
      font-size: 14px;
    }
    .field-value {
      flex: 1;
      font-size: 14px;
      color: #222;
      border-bottom: 1px dotted #aaa;
      padding-left: 8px;
    }
    .section-title {
      font-weight: bold;
      margin: 20px 0 10px;
      font-size: 16px;
      background: #f5f5f5;
      padding: 6px 10px;
      border-left: 4px solid #8b0000;
    }
    .signature-area {
      margin-top: 36px;
      display: flex;
      justify-content: space-between;
      padding-top: 20px;
      border-top: 1px dashed #ccc;
    }
    .signature {
      text-align: center;
      width: 200px;
    }
    .signature-line {
      margin-top: 40px;
      border-top: 1px solid #333;
      width: 100%;
    }
    .signature p {
      margin-top: 8px;
      font-size: 12px;
      color: #555;
    }
    .footer {
      text-align: center;
      font-size: 11px;
      color: #666;
      padding: 15px;
      border-top: 1px solid #eee;
      margin-top: 20px;
    }
  </style>
</head>
<body>
<div class="leave-form">
  <div class="header">
    <h1>LEAVE APPLICATION FORM</h1>
    <h2>Arabian Shield Manpower LLC.</h2>
  </div>
  <div class="content">
    <div class="field-row">
      <div class="field-label">EMPLOYEE NAME</div>
      <div class="field-value">${req.employee.fullName}</div>
    </div>
    <div class="field-row">
      <div class="field-label">EMIRATES ID / EMPLOYEE ID</div>
      <div class="field-value">${req.employee.employeeId}</div>
    </div>
    <div class="field-row">
      <div class="field-label">DESIGNATION</div>
      <div class="field-value">${req.employee.position || '—'}</div>
    </div>
    <div class="field-row">
      <div class="field-label">COMPANY NAME</div>
      <div class="field-value">${req.employee.companyName || '—'}</div>
    </div>
    <div class="field-row">
      <div class="field-label">CONTACT NUMBER</div>
      <div class="field-value">${req.employee.phone || '—'}</div>
    </div>
    <div class="field-row">
      <div class="field-label">APP. SUBMISSION DATE</div>
      <div class="field-value">${submissionDate}</div>
    </div>

    <div class="section-title">Leave Details</div>
    <div class="field-row">
      <div class="field-label">Type of Leave</div>
      <div class="field-value">${leaveType}</div>
    </div>
    <div class="field-row">
      <div class="field-label">Leave Period</div>
      <div class="field-value">From: ${formatFormalDate(req.startDate)} &nbsp;&nbsp; To: ${formatFormalDate(req.endDate)}</div>
    </div>
    <div class="field-row">
      <div class="field-label">Total No. of Days</div>
      <div class="field-value">${req.totalDays} DAYS</div>
    </div>

    <div class="section-title">Reason for Leave</div>
    <div class="field-row">
      <div class="field-value" style="border:none; white-space: pre-wrap;">${req.reason}</div>
    </div>

    <div class="signature-area">
      <div class="signature">
        <div class="signature-line"></div>
        <p>Employee Signature</p>
      </div>
      <div class="signature">
        <div class="signature-line"></div>
        <p>HR / OFFICE ADMIN</p>
      </div>
    </div>
  </div>
  <div class="footer">
    This is a computer generated document – no signature required.
  </div>
</div>
</body>
</html>`;
}

function printLeaveRequest(req: LeaveRequest) {
  const html = generateLeaveApplicationHtml(req);
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
  } else {
    toast({ title: 'Error', description: 'Please allow pop-ups to print.', variant: 'destructive' });
  }
}

/* ───────── Skeleton Cards ───────── */
function SkeletonCards({ count = 3 }: { count?: number }) {
  return (
    <div className="flex flex-col gap-3">
      {Array.from({ length: count }).map((_, i) => (
        <Skeleton key={i} className="h-28 w-full rounded-xl bg-slate-700/50" />
      ))}
    </div>
  );
}

/* ───────── Empty State ───────── */
function EmptyState({ icon: Icon, message }: { icon: React.ElementType; message: string }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-center">
      <div className="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-700/50 mb-4">
        <Icon className="h-7 w-7 text-slate-500" />
      </div>
      <p className="text-sm text-slate-400">{message}</p>
    </div>
  );
}

/* ───────── Generic Request Card ───────── */
interface RequestCardProps {
  id: string;
  employeeName: string;
  employeeCode: string;
  details: React.ReactNode;
  createdAt: string;
  status: 'pending' | 'approved' | 'rejected';
  onApprove?: () => void;
  onReject?: () => void;
  showActions?: boolean;
  extraActions?: React.ReactNode;
}

function RequestCard({
  employeeName,
  employeeCode,
  details,
  createdAt,
  status,
  onApprove,
  onReject,
  showActions = true,
  extraActions,
}: RequestCardProps) {
  const statusConfig = {
    pending: { color: 'bg-amber-500/20 text-amber-400 border-amber-500/30', icon: HourglassIcon, label: 'Pending' },
    approved: { color: 'bg-green-500/20 text-green-400 border-green-500/30', icon: CheckCircle2, label: 'Approved' },
    rejected: { color: 'bg-red-500/20 text-red-400 border-red-500/30', icon: XCircle, label: 'Rejected' },
  };
  const cfg = statusConfig[status];
  const StatusIcon = cfg.icon;

  return (
    <div className="bg-slate-800 rounded-xl border border-slate-700 p-4 hover:bg-slate-700/50 transition-colors">
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-2 flex-wrap">
            <span className="text-sm font-semibold text-white truncate">{employeeName}</span>
            <Badge variant="outline" className="text-[10px] font-mono px-1.5 py-0 border-slate-600 text-slate-400">
              {employeeCode}
            </Badge>
            <Badge className={cn('text-xs px-2 py-0.5 border', cfg.color)}>
              <StatusIcon className="h-3 w-3 mr-1" />
              {cfg.label}
            </Badge>
          </div>
          <div className="text-xs text-slate-300 space-y-1">{details}</div>
          <div className="mt-2 text-[11px] text-slate-500 flex items-center gap-1">
            <Clock className="h-3 w-3" />
            {formatDate(createdAt)}
          </div>
        </div>
        {showActions && status === 'pending' && (onApprove || onReject) && (
          <div className="flex flex-col sm:flex-row gap-1.5 shrink-0">
            {onApprove && (
              <Button
                size="sm"
                onClick={onApprove}
                className="h-7 px-2.5 bg-green-600 hover:bg-green-700 text-white text-xs"
              >
                <CheckCircle2 className="h-3.5 w-3.5 mr-1" />
                Approve
              </Button>
            )}
            {onReject && (
              <Button
                size="sm"
                onClick={onReject}
                className="h-7 px-2.5 bg-red-600 hover:bg-red-700 text-white text-xs"
              >
                <XCircle className="h-3.5 w-3.5 mr-1" />
                Reject
              </Button>
            )}
            {extraActions}
          </div>
        )}
      </div>
    </div>
  );
}

/* ───────── Employee Search Combobox (reused) ───────── */
function EmployeeSearchCombobox({
  employees,
  onSelect,
  selectedId,
}: {
  employees: EmployeeOption[];
  onSelect: (emp: EmployeeOption) => void;
  selectedId: string | null;
}) {
  const [open, setOpen] = useState(false);
  const selectedEmployee = useMemo(
    () => employees.find((e) => e.id === selectedId),
    [employees, selectedId]
  );

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          className="w-full justify-between bg-slate-800 border-slate-700 text-white hover:bg-slate-700 hover:text-white text-sm"
        >
          {selectedEmployee
            ? `${selectedEmployee.fullName} (${selectedEmployee.employeeId})`
            : 'Search employees...'}
          <SearchIcon className="ml-2 h-4 w-4 shrink-0 opacity-50" />
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[var(--radix-popover-trigger-width)] p-0 bg-slate-800 border-slate-600" align="start">
        <Command className="bg-slate-800">
          <CommandInput placeholder="Type to search..." className="text-white" />
          <CommandList>
            <CommandEmpty className="text-slate-400">No employees found.</CommandEmpty>
            <CommandGroup>
              {employees.map((emp) => (
                <CommandItem
                  key={emp.id}
                  value={`${emp.fullName} ${emp.employeeId} ${emp.position || ''}`}
                  onSelect={() => {
                    onSelect(emp);
                    setOpen(false);
                  }}
                  className="text-slate-200 data-[selected=true]:bg-slate-700 data-[selected=true]:text-white"
                >
                  <div className="flex flex-col">
                    <span className="text-sm">{emp.fullName}</span>
                    <span className="text-[11px] text-slate-500">
                      {emp.employeeId}
                      {emp.position ? ` · ${emp.position}` : ''}
                    </span>
                  </div>
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
}

/* ───────── Leave Requests Sub-Tab ───────── */
function LeaveRequestsTab({ userId, isSuperAdmin }: { userId: string; isSuperAdmin: boolean }) {
  const [requests, setRequests] = useState<LeaveRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [yearFilter, setYearFilter] = useState<string>(String(currentYear));
  const [monthFilter, setMonthFilter] = useState<string>('all');
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
  const [leaveType, setLeaveType] = useState<string>('casual');
  const [otherTypeText, setOtherTypeText] = useState('');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [totalDays, setTotalDays] = useState(0);
  const [reason, setReason] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);

  const fetchEmployees = useCallback(async () => {
    setEmployeesLoading(true);
    try {
      const res = await fetch('/api/employees?status=active&limit=1000');
      const data = await res.json();
      if (data.success && data.data?.employees) {
        setEmployees(
          data.data.employees.map((e: any) => ({
            id: e.id,
            fullName: e.fullName,
            employeeId: e.employeeId,
            phone: e.phone,
            position: e.position,
            companyName: e.companyName,
            nationality: e.nationality,
            currentSite: e.currentSite,
          }))
        );
      }
    } catch {
      // ignore
    } finally {
      setEmployeesLoading(false);
    }
  }, []);

  const fetchRequests = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (statusFilter !== 'all') params.set('status', statusFilter);
      const res = await fetch(`/api/leave-requests?${params.toString()}`);
      const data = await res.json();
      if (data.success) {
        let filtered = data.data.leaveRequests || [];
        if (yearFilter !== 'all') filtered = filtered.filter((r: LeaveRequest) => r.createdAt.startsWith(yearFilter));
        if (monthFilter !== 'all') filtered = filtered.filter((r: LeaveRequest) => r.createdAt.substring(5, 7) === monthFilter);
        setRequests(filtered);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch leave requests', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, [statusFilter, yearFilter, monthFilter]);

  useEffect(() => { fetchRequests(); }, [fetchRequests]);

  useEffect(() => {
    if (startDate && endDate) setTotalDays(calculateTotalDays(startDate, endDate));
    else setTotalDays(0);
  }, [startDate, endDate]);

  const openCreateDialog = useCallback(() => {
    setSelectedEmployee(null);
    setLeaveType('casual');
    setOtherTypeText('');
    setStartDate('');
    setEndDate('');
    setReason('');
    if (employees.length === 0) fetchEmployees();
    setCreateDialogOpen(true);
  }, [employees.length, fetchEmployees]);

  const handleCreate = async () => {
    if (!selectedEmployee || !startDate || !endDate || !reason.trim()) {
      toast({ title: 'Validation Error', description: 'Please fill all required fields.', variant: 'destructive' });
      return;
    }
    if (new Date(startDate) > new Date(endDate)) {
      toast({ title: 'Invalid Dates', description: 'End date must be after start date.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    try {
      const payload = {
        employeeId: selectedEmployee.id,
        type: leaveType,
        otherTypeText: leaveType === 'other' ? otherTypeText : null,
        startDate,
        endDate,
        totalDays,
        reason,
        createdById: userId,
      };
      const res = await fetch('/api/leave-requests', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: 'Leave Request Submitted', description: 'Your request has been sent for approval.' });
        setCreateDialogOpen(false);
        fetchRequests();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to submit', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to submit leave request', variant: 'destructive' });
    } finally {
      setSubmitting(false);
    }
  };

  const handleReview = async (id: string, status: 'approved' | 'rejected') => {
    try {
      const res = await fetch(`/api/leave-requests/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status, reviewedBy: userId }),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: status === 'approved' ? 'Approved' : 'Rejected', description: `Leave request ${status}` });
        fetchRequests();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to update', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to update request', variant: 'destructive' });
    }
  };

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap gap-2">
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-32 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue placeholder="Status" />
            </SelectTrigger>
            <SelectContent className="bg-slate-800 border-slate-600">
              <SelectItem value="all">All</SelectItem>
              <SelectItem value="pending">Pending</SelectItem>
              <SelectItem value="approved">Approved</SelectItem>
              <SelectItem value="rejected">Rejected</SelectItem>
            </SelectContent>
          </Select>
          <Select value={yearFilter} onValueChange={setYearFilter}>
            <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Years</SelectItem>
              {YEARS.map(y => <SelectItem key={y} value={y}>{y}</SelectItem>)}
            </SelectContent>
          </Select>
          <Select value={monthFilter} onValueChange={setMonthFilter}>
            <SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Months</SelectItem>
              {MONTHS.map(m => <SelectItem key={m.value} value={m.value}>{m.label}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
        <Button size="sm" onClick={openCreateDialog} className="h-8 bg-blue-600 hover:bg-blue-700 text-white text-xs gap-1.5">
          <Plus className="h-3.5 w-3.5" /> New Leave Request
        </Button>
      </div>

      <div className="max-h-[600px] overflow-y-auto custom-scrollbar flex flex-col gap-3 pr-1">
        {loading ? <SkeletonCards /> : requests.length === 0 ? <EmptyState icon={CalendarDays} message="No leave requests found" /> : (
          requests.map(req => (
            <RequestCard
              key={req.id}
              id={req.id}
              employeeName={req.employee.fullName}
              employeeCode={req.employee.employeeId}
              createdAt={req.createdAt}
              status={req.status}
              onApprove={isSuperAdmin ? () => handleReview(req.id, 'approved') : undefined}
              onReject={isSuperAdmin ? () => handleReview(req.id, 'rejected') : undefined}
              showActions={isSuperAdmin && req.status === 'pending'}
              extraActions={
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => printLeaveRequest(req)}
                  className="h-7 px-2 text-xs text-slate-400 hover:text-white"
                >
                  <Printer className="h-3.5 w-3.5 mr-1" /> Print
                </Button>
              }
              details={
                <div className="space-y-0.5">
                  <div><span className="text-slate-500">Type:</span> {req.type}{req.type === 'other' && req.otherTypeText ? ` (${req.otherTypeText})` : ''}</div>
                  <div><span className="text-slate-500">Period:</span> {formatDate(req.startDate)} → {formatDate(req.endDate)} ({req.totalDays} days)</div>
                  <div><span className="text-slate-500">Reason:</span> {req.reason}</div>
                </div>
              }
            />
          ))
        )}
      </div>

      {/* Create Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
          <DialogHeader>
            <DialogTitle>New Leave Request</DialogTitle>
            <DialogDescription>Fill in the leave application details.</DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-2">
            <div>
              <Label>Employee</Label>
              {employeesLoading ? <div className="text-slate-400 text-sm">Loading...</div> : (
                <EmployeeSearchCombobox employees={employees} onSelect={setSelectedEmployee} selectedId={selectedEmployee?.id || null} />
              )}
            </div>
            <div>
              <Label>Type of Leave</Label>
              <Select value={leaveType} onValueChange={setLeaveType}>
                <SelectTrigger className="bg-slate-900 border-slate-700 text-white"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="casual">Casual</SelectItem>
                  <SelectItem value="sick">Sick</SelectItem>
                  <SelectItem value="annual">Annual</SelectItem>
                  <SelectItem value="emergency">Emergency</SelectItem>
                  <SelectItem value="marriage">Marriage</SelectItem>
                  <SelectItem value="other">Other</SelectItem>
                </SelectContent>
              </Select>
              {leaveType === 'other' && (
                <Input placeholder="Specify leave type" value={otherTypeText} onChange={e => setOtherTypeText(e.target.value)} className="mt-2 bg-slate-900 border-slate-700 text-white" />
              )}
            </div>
            <div className="grid grid-cols-2 gap-2">
              <div><Label>Start Date</Label><Input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} className="bg-slate-900 border-slate-700 text-white" /></div>
              <div><Label>End Date</Label><Input type="date" value={endDate} onChange={e => setEndDate(e.target.value)} className="bg-slate-900 border-slate-700 text-white" /></div>
            </div>
            {totalDays > 0 && <p className="text-xs text-slate-400">Total days: {totalDays}</p>}
            <div><Label>Reason</Label><Textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Detailed reason for leave" className="bg-slate-900 border-slate-700 text-white resize-none" /></div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateDialogOpen(false)} className="border-slate-600">Cancel</Button>
            <Button onClick={handleCreate} disabled={submitting || !selectedEmployee || !startDate || !endDate || !reason.trim()} className="bg-blue-600 hover:bg-blue-700">
              {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Submit Request'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

/* ───────── Cancellation Requests Sub-Tab ───────── */
function CancellationRequestsTab({ userId, isSuperAdmin }: { userId: string; isSuperAdmin: boolean }) {
  const [requests, setRequests] = useState<CancellationRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [yearFilter, setYearFilter] = useState<string>(String(currentYear));
  const [monthFilter, setMonthFilter] = useState<string>('all');
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
  const [reason, setReason] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);

  const fetchEmployees = useCallback(async () => {
    setEmployeesLoading(true);
    try {
      const res = await fetch('/api/employees?status=active&limit=1000');
      const data = await res.json();
      if (data.success && data.data?.employees) {
        setEmployees(data.data.employees.map((e: any) => ({ id: e.id, fullName: e.fullName, employeeId: e.employeeId, phone: e.phone, position: e.position, companyName: e.companyName, nationality: e.nationality, currentSite: e.currentSite })));
      }
    } catch { } finally { setEmployeesLoading(false); }
  }, []);

  const fetchRequests = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (statusFilter !== 'all') params.set('status', statusFilter);
      const res = await fetch(`/api/cancellation-requests?${params.toString()}`);
      const data = await res.json();
      if (data.success) {
        let filtered = data.data.cancellationRequests || [];
        if (yearFilter !== 'all') filtered = filtered.filter(r => r.createdAt.startsWith(yearFilter));
        if (monthFilter !== 'all') filtered = filtered.filter(r => r.createdAt.substring(5, 7) === monthFilter);
        setRequests(filtered);
      }
    } catch { toast({ title: 'Error', description: 'Failed to fetch cancellation requests', variant: 'destructive' }); } finally { setLoading(false); }
  }, [statusFilter, yearFilter, monthFilter]);

  useEffect(() => { fetchRequests(); }, [fetchRequests]);

  const openCreateDialog = useCallback(() => {
    setSelectedEmployee(null);
    setReason('');
    if (employees.length === 0) fetchEmployees();
    setCreateDialogOpen(true);
  }, [employees.length, fetchEmployees]);

  const handleCreate = async () => {
    if (!selectedEmployee || !reason.trim()) {
      toast({ title: 'Validation Error', description: 'Please select an employee and provide a reason.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    try {
      const res = await fetch('/api/cancellation-requests', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ employeeId: selectedEmployee.id, reason, createdById: userId }),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: 'Cancellation Request Submitted' });
        setCreateDialogOpen(false);
        fetchRequests();
      } else toast({ title: 'Error', description: data.error, variant: 'destructive' });
    } catch { toast({ title: 'Error', description: 'Failed to submit', variant: 'destructive' }); } finally { setSubmitting(false); }
  };

  const handleReview = async (id: string, status: 'approved' | 'rejected') => {
    try {
      const res = await fetch(`/api/cancellation-requests/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status, reviewedBy: userId }),
      });
      const data = await res.json();
      if (data.success) { toast({ title: status === 'approved' ? 'Approved' : 'Rejected' }); fetchRequests(); }
      else toast({ title: 'Error', description: data.error, variant: 'destructive' });
    } catch { toast({ title: 'Error', description: 'Failed to update', variant: 'destructive' }); }
  };

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap gap-2">
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-32 bg-slate-800 border-slate-700 text-sm text-white"><SelectValue /></SelectTrigger>
            <SelectContent className="bg-slate-800 border-slate-600"><SelectItem value="all">All</SelectItem><SelectItem value="pending">Pending</SelectItem><SelectItem value="approved">Approved</SelectItem><SelectItem value="rejected">Rejected</SelectItem></SelectContent>
          </Select>
          <Select value={yearFilter} onValueChange={setYearFilter}><SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white"><SelectValue /></SelectTrigger><SelectContent className="bg-slate-800 border-slate-600">{YEARS.map(y => <SelectItem key={y} value={y}>{y}</SelectItem>)}</SelectContent></Select>
          <Select value={monthFilter} onValueChange={setMonthFilter}><SelectTrigger className="w-28 bg-slate-800 border-slate-700 text-sm text-white"><SelectValue /></SelectTrigger><SelectContent className="bg-slate-800 border-slate-600">{MONTHS.map(m => <SelectItem key={m.value} value={m.value}>{m.label}</SelectItem>)}</SelectContent></Select>
        </div>
        <Button size="sm" onClick={openCreateDialog} className="h-8 bg-red-600 hover:bg-red-700 text-white text-xs gap-1.5"><Plus className="h-3.5 w-3.5" /> New Cancellation Request</Button>
      </div>

      <div className="max-h-[600px] overflow-y-auto flex flex-col gap-3 pr-1">
        {loading ? <SkeletonCards /> : requests.length === 0 ? <EmptyState icon={Ban} message="No cancellation requests found" /> : (
          requests.map(req => (
            <RequestCard
              key={req.id}
              id={req.id}
              employeeName={req.employee.fullName}
              employeeCode={req.employee.employeeId}
              createdAt={req.createdAt}
              status={req.status}
              onApprove={isSuperAdmin ? () => handleReview(req.id, 'approved') : undefined}
              onReject={isSuperAdmin ? () => handleReview(req.id, 'rejected') : undefined}
              showActions={isSuperAdmin && req.status === 'pending'}
              details={<div><span className="text-slate-500">Reason:</span> {req.reason}</div>}
            />
          ))
        )}
      </div>

      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
          <DialogHeader><DialogTitle>New Cancellation Request</DialogTitle><DialogDescription>Provide reason for cancellation.</DialogDescription></DialogHeader>
          <div className="flex flex-col gap-4 py-2">
            <div><Label>Employee</Label>{employeesLoading ? <div className="text-slate-400">Loading...</div> : <EmployeeSearchCombobox employees={employees} onSelect={setSelectedEmployee} selectedId={selectedEmployee?.id || null} />}</div>
            <div><Label>Reason</Label><Textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Reason for cancellation" className="bg-slate-900 border-slate-700 text-white resize-none" /></div>
          </div>
          <DialogFooter><Button variant="outline" onClick={() => setCreateDialogOpen(false)} className="border-slate-600">Cancel</Button><Button onClick={handleCreate} disabled={submitting || !selectedEmployee || !reason.trim()} className="bg-red-600 hover:bg-red-700">{submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Submit'}</Button></DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

/* ───────── Warnings Tab ───────── */
function WarningsTab({ userId }: { userId: string }) {
  const [warnings, setWarnings] = useState<Warning[]>([]);
  const [loading, setLoading] = useState(true);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
  const [reason, setReason] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);

  const fetchEmployees = useCallback(async () => {
    setEmployeesLoading(true);
    try {
      const res = await fetch('/api/employees?status=active&limit=1000');
      const data = await res.json();
      if (data.success && data.data?.employees) {
        setEmployees(data.data.employees.map((e: any) => ({ id: e.id, fullName: e.fullName, employeeId: e.employeeId, phone: e.phone, position: e.position, companyName: e.companyName, nationality: e.nationality, currentSite: e.currentSite })));
      }
    } catch { } finally { setEmployeesLoading(false); }
  }, []);

  const fetchWarnings = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/warnings');
      const data = await res.json();
      if (data.success) {
        setWarnings(data.data.warnings || []);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch warnings', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchWarnings(); }, [fetchWarnings]);

  const openCreateDialog = useCallback(() => {
    setSelectedEmployee(null);
    setReason('');
    if (employees.length === 0) fetchEmployees();
    setCreateDialogOpen(true);
  }, [employees.length, fetchEmployees]);

  const handleCreate = async () => {
    if (!selectedEmployee || !reason.trim()) {
      toast({ title: 'Validation Error', description: 'Please select an employee and provide a reason.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    try {
      const res = await fetch('/api/warnings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ employeeId: selectedEmployee.id, reason, createdById: userId }),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: 'Warning Issued', description: `Warning has been issued for ${selectedEmployee.fullName}.` });
        setCreateDialogOpen(false);
        fetchWarnings();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to issue warning', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to issue warning', variant: 'destructive' });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex flex-col gap-3">
      <div className="flex justify-end">
        <Button size="sm" onClick={openCreateDialog} className="h-8 bg-orange-600 hover:bg-orange-700 text-white text-xs gap-1.5">
          <Plus className="h-3.5 w-3.5" /> Add New Warning
        </Button>
      </div>
      {loading ? <SkeletonCards /> : warnings.length === 0 ? <EmptyState icon={AlertTriangle} message="No warnings found" /> : (
        warnings.map(w => (
          <div key={w.id} className="bg-slate-800 rounded-xl border border-slate-700 p-4 hover:bg-slate-700/50 transition-colors">
            <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-2 flex-wrap">
                  <span className="text-sm font-semibold text-white truncate">{w.employee.fullName}</span>
                  <Badge variant="outline" className="text-[10px] font-mono px-1.5 py-0 border-slate-600 text-slate-400">{w.employee.employeeId}</Badge>
                  {w.isAutoGenerated && <Badge className="text-xs px-2 py-0.5 bg-amber-500/20 text-amber-400 border border-amber-500/30">Auto</Badge>}
                  <Badge className="text-xs px-2 py-0.5 bg-orange-500/20 text-orange-400 border border-orange-500/30"><AlertTriangle className="h-3 w-3 mr-1" />Warning</Badge>
                </div>
                <div className="text-xs text-slate-300 space-y-1">
                  <div><span className="text-slate-500">Reason:</span> {w.reason}</div>
                  {w.absentDates && <div><span className="text-slate-500">Absent dates:</span> {w.absentDates}</div>}
                  <div><span className="text-slate-500">Issued by:</span> {w.createdBy.name}</div>
                </div>
                <div className="mt-2 text-[11px] text-slate-500 flex items-center gap-1">
                  <Clock className="h-3 w-3" />
                  {formatDate(w.createdAt)}
                </div>
              </div>
            </div>
          </div>
        ))
      )}

      {/* Create Warning Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Issue New Warning</DialogTitle>
            <DialogDescription>Issue a warning to an employee. This will deduct 0.5 stars from their rating.</DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-2">
            <div>
              <Label>Employee</Label>
              {employeesLoading ? <div className="text-slate-400 text-sm">Loading...</div> : (
                <EmployeeSearchCombobox employees={employees} onSelect={setSelectedEmployee} selectedId={selectedEmployee?.id || null} />
              )}
            </div>
            <div>
              <Label>Reason</Label>
              <Textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Detailed reason for the warning" className="bg-slate-900 border-slate-700 text-white resize-none" />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateDialogOpen(false)} className="border-slate-600">Cancel</Button>
            <Button onClick={handleCreate} disabled={submitting || !selectedEmployee || !reason.trim()} className="bg-orange-600 hover:bg-orange-700">
              {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Issue Warning'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

/* ───────── Fines Tab ───────── */
function FinesTab({ userId }: { userId: string }) {
  const [fines, setFines] = useState<Fine[]>([]);
  const [loading, setLoading] = useState(true);
  const [createDialogOpen, setCreateDialogOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<EmployeeOption | null>(null);
  const [reason, setReason] = useState('');
  const [amount, setAmount] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [employeesLoading, setEmployeesLoading] = useState(false);

  const fetchEmployees = useCallback(async () => {
    setEmployeesLoading(true);
    try {
      const res = await fetch('/api/employees?status=active&limit=1000');
      const data = await res.json();
      if (data.success && data.data?.employees) {
        setEmployees(data.data.employees.map((e: any) => ({ id: e.id, fullName: e.fullName, employeeId: e.employeeId, phone: e.phone, position: e.position, companyName: e.companyName, nationality: e.nationality, currentSite: e.currentSite })));
      }
    } catch { } finally { setEmployeesLoading(false); }
  }, []);

  const fetchFines = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/fines');
      const data = await res.json();
      if (data.success) {
        setFines(data.data.fines || []);
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to fetch fines', variant: 'destructive' });
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchFines(); }, [fetchFines]);

  const openCreateDialog = useCallback(() => {
    setSelectedEmployee(null);
    setReason('');
    setAmount('');
    if (employees.length === 0) fetchEmployees();
    setCreateDialogOpen(true);
  }, [employees.length, fetchEmployees]);

  const handleCreate = async () => {
    if (!selectedEmployee || !reason.trim() || !amount) {
      toast({ title: 'Validation Error', description: 'Please fill in all required fields.', variant: 'destructive' });
      return;
    }
    const numAmount = parseFloat(amount);
    if (isNaN(numAmount) || numAmount < 0) {
      toast({ title: 'Invalid Amount', description: 'Amount must be a positive number.', variant: 'destructive' });
      return;
    }
    setSubmitting(true);
    try {
      const res = await fetch('/api/fines', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ employeeId: selectedEmployee.id, reason, amount: numAmount, createdById: userId }),
      });
      const data = await res.json();
      if (data.success) {
        toast({ title: 'Fine Issued', description: `Fine of ${formatCurrency(numAmount)} has been issued for ${selectedEmployee.fullName}.` });
        setCreateDialogOpen(false);
        fetchFines();
      } else {
        toast({ title: 'Error', description: data.error || 'Failed to issue fine', variant: 'destructive' });
      }
    } catch {
      toast({ title: 'Error', description: 'Failed to issue fine', variant: 'destructive' });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="flex flex-col gap-3">
      <div className="flex justify-end">
        <Button size="sm" onClick={openCreateDialog} className="h-8 bg-red-600 hover:bg-red-700 text-white text-xs gap-1.5">
          <Plus className="h-3.5 w-3.5" /> Add New Fine
        </Button>
      </div>
      {loading ? <SkeletonCards /> : fines.length === 0 ? <EmptyState icon={DollarSign} message="No fines found" /> : (
        fines.map(f => (
          <div key={f.id} className="bg-slate-800 rounded-xl border border-slate-700 p-4 hover:bg-slate-700/50 transition-colors">
            <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-2 flex-wrap">
                  <span className="text-sm font-semibold text-white truncate">{f.employee.fullName}</span>
                  <Badge variant="outline" className="text-[10px] font-mono px-1.5 py-0 border-slate-600 text-slate-400">{f.employee.employeeId}</Badge>
                  <Badge className="text-xs px-2 py-0.5 bg-red-500/20 text-red-400 border border-red-500/30"><DollarSign className="h-3 w-3 mr-1" />{formatCurrency(f.amount)}</Badge>
                </div>
                <div className="text-xs text-slate-300 space-y-1">
                  <div><span className="text-slate-500">Reason:</span> {f.reason}</div>
                  <div><span className="text-slate-500">Issued by:</span> {f.createdBy.name}</div>
                </div>
                <div className="mt-2 text-[11px] text-slate-500 flex items-center gap-1">
                  <Clock className="h-3 w-3" />
                  {formatDate(f.createdAt)}
                </div>
              </div>
            </div>
          </div>
        ))
      )}

      {/* Create Fine Dialog */}
      <Dialog open={createDialogOpen} onOpenChange={setCreateDialogOpen}>
        <DialogContent className="bg-slate-800 border-slate-700 text-white sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Issue New Fine</DialogTitle>
            <DialogDescription>Issue a fine to an employee. This will deduct 1 star from their rating.</DialogDescription>
          </DialogHeader>
          <div className="flex flex-col gap-4 py-2">
            <div>
              <Label>Employee</Label>
              {employeesLoading ? <div className="text-slate-400 text-sm">Loading...</div> : (
                <EmployeeSearchCombobox employees={employees} onSelect={setSelectedEmployee} selectedId={selectedEmployee?.id || null} />
              )}
            </div>
            <div>
              <Label>Amount (SAR)</Label>
              <Input type="number" min="0" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" className="bg-slate-900 border-slate-700 text-white" />
            </div>
            <div>
              <Label>Reason</Label>
              <Textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Detailed reason for the fine" className="bg-slate-900 border-slate-700 text-white resize-none" />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setCreateDialogOpen(false)} className="border-slate-600">Cancel</Button>
            <Button onClick={handleCreate} disabled={submitting || !selectedEmployee || !reason.trim() || !amount} className="bg-red-600 hover:bg-red-700">
              {submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Issue Fine'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

/* ───────── Main Page ───────── */
export function NotificationPage() {
  const { user } = useAuthStore();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [loading, setLoading] = useState(true);
  const isSuperAdmin = user?.role === 'super_admin';
  const userId = user?.id || '';

  const fetchNotifications = useCallback(async () => {
    try {
      const res = await fetch('/api/notifications?limit=100');
      const data = await res.json();
      if (data.success) {
        const notifs: Notification[] = data.data.notifications || [];
        setNotifications(notifs);
        setUnreadCount(notifs.filter((n) => !n.read).length);
      }
    } catch { } finally { setLoading(false); }
  }, []);

  useEffect(() => { fetchNotifications(); }, [fetchNotifications]);

  const handleMarkAllRead = async () => {
    try {
      await fetch('/api/notifications', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ markAll: true }) });
      setNotifications(prev => prev.map(n => ({ ...n, read: true })));
      setUnreadCount(0);
      toast({ title: 'All notifications marked as read' });
    } catch { toast({ title: 'Error', description: 'Failed to mark all as read', variant: 'destructive' }); }
  };

  return (
    <div className="flex flex-col gap-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10"><Bell className="h-5 w-5 text-blue-400" /></div>
          <div><h2 className="text-2xl font-bold text-white flex items-center gap-2">Notifications{!loading && unreadCount > 0 && <Badge className="bg-blue-500 text-white">{unreadCount}</Badge>}</h2><p className="text-slate-400 text-sm">Stay updated with requests, warnings, and fines</p></div>
        </div>
        {unreadCount > 0 && <Button variant="outline" size="sm" onClick={handleMarkAllRead} className="h-8 border-slate-600 text-slate-300 hover:text-white hover:bg-slate-700 text-xs"><CheckCheck className="h-3.5 w-3.5 mr-1.5" />Mark All Read</Button>}
      </div>

      <Tabs defaultValue="requests" className="w-full">
        <TabsList className="bg-slate-800 border border-slate-700/50">
          <TabsTrigger value="requests" className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"><FileText className="h-4 w-4" />Requests</TabsTrigger>
          <TabsTrigger value="warnings" className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"><AlertTriangle className="h-4 w-4" />Warnings</TabsTrigger>
          <TabsTrigger value="fines" className="data-[state=active]:bg-slate-700 data-[state=active]:text-white text-slate-400 gap-1.5 px-4"><DollarSign className="h-4 w-4" />Fines</TabsTrigger>
        </TabsList>

        <TabsContent value="requests" className="mt-4">
          <Tabs defaultValue="leave" className="w-full">
            <TabsList className="bg-slate-800/50 mb-3">
              <TabsTrigger value="leave" className="data-[state=active]:bg-slate-700 data-[state=active]:text-white"><CalendarDays className="h-3.5 w-3.5 mr-1" /> Leave Requests</TabsTrigger>
              <TabsTrigger value="cancellation" className="data-[state=active]:bg-slate-700 data-[state=active]:text-white"><Ban className="h-3.5 w-3.5 mr-1" /> Cancellation Requests</TabsTrigger>
            </TabsList>
            <TabsContent value="leave"><LeaveRequestsTab userId={userId} isSuperAdmin={isSuperAdmin} /></TabsContent>
            <TabsContent value="cancellation"><CancellationRequestsTab userId={userId} isSuperAdmin={isSuperAdmin} /></TabsContent>
          </Tabs>
        </TabsContent>

        <TabsContent value="warnings" className="mt-4"><WarningsTab userId={userId} /></TabsContent>
        <TabsContent value="fines" className="mt-4"><FinesTab userId={userId} /></TabsContent>
      </Tabs>
    </div>
  );
}